### ISSUE TITLE
Incorrect Time Zone settings

### ISSUE THREAD

**Issue by ashishpahwa7** [ACE-VSIT/Library-Portal#9]
```
`Traceback (most recent call last):
 File "manage.py", line 10, in <module>
 execute_from_command_line(sys.argv)
 File "/home/ash/acelibrary/local/lib/python2.7/site-packages/django/core/management/__init__.py",     line 353, in execute_from_command_line
utility.execute()
File "/home/ash/acelibrary/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 302, in execute
settings.INSTALLED_APPS
File "/home/ash/acelibrary/local/lib/python2.7/site-packages/django/conf/__init__.py", line 55, in __getattr__
self._setup(name)
File "/home/ash/acelibrary/local/lib/python2.7/site-packages/django/conf/__init__.py", line 43, in _setup
self._wrapped = Settings(settings_module)
File "/home/ash/acelibrary/local/lib/python2.7/site-packages/django/conf/__init__.py", line 138, in __init__
raise ValueError("Incorrect timezone setting: %s" % self.TIME_ZONE)
```

ValueError: Incorrect timezone setting: UTC+09
`

**Comment by ashishpahwa7** [comment]
fixed #11
